spring:
  datasource:
    url: jdbc:h2:mem:studentdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      path: /h2-console
      enabled: true
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8083

